/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baitapsql;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class FrmClient1 extends javax.swing.JFrame {

    FileOutputStream f;
    int ktNhanfile = 0;
    GoiNhan gn = new GoiNhan();
    static Thread tdnhanfile;

    /**
     * Creates new form FrmClient
     */
    public FrmClient1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        choice1 = new java.awt.Choice();
        jButton1 = new javax.swing.JButton();
        list1 = new java.awt.List();
        txtsend = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Chọn Người Nhắn Tin");

        jButton1.setText("Nhap lai Ten Dang Nhap");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Gửi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Gửi FILE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jMenu3.setText("Tài Khoản    ");

        jMenuItem3.setText("Đăng ký");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem3MousePressed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Thoát");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem4MousePressed(evt);
            }
        });
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Thông tin cá nhân");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu4MousePressed(evt);
            }
        });

        jMenuItem2.setText("Lưu tin");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem2MousePressed(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem5.setText("Hiện Thị Thông Tin");
        jMenuItem5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem5MousePressed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem6.setText("Đổi Mật Khẩu");
        jMenuItem6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem6MousePressed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(list1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtsend, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)))
                .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtsend)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public class ThreadGoiTinNhan extends Thread {

        public void run() {
            while (true) {
                try {
                    if (ktNhanfile == 0)//Nếu gửi thông báo
                    {
                        System.out.print("Dang cho:");
                        String dulieu = gn.Nhan();//Chờ và nhận dữ liệu gửi về
                        //Qui ước: nếu ký tự đầu là khoảng trắng là gửi thông báo
                        //Nếu 4 ký tự đầu là: “/tf:” là gửi tên file cần chuyển
                        if (dulieu.substring(0, 4).equals("/tf:")) {//Nếu người dùng gửi tên file
                            list1.add("Dang nhan file: " + dulieu);//Hiển thị tên file cần gửi
                            String TenFileNhan = dulieu.substring(4, dulieu.length());//Lấy tên file
                            f = new FileOutputStream("d:\\" + TenFileNhan);//Tạo ra 1 file có tên vừa nhận lưu vào ổ d
                            ktNhanfile = 1;//Bắt đầu nhận file
                            tdnhanfile = new Thread(new ThreadNhanFile());//Tạo ra tuyến đoạn để nhận file
                            tdnhanfile.start();//Bắt đầu tuyến đoạn -> bắt đầu nhận file
                        } else {
                            list1.add(dulieu); //Hiển thị dữ liệu ra list1
                            ktNhanfile =0;
                        }
                        System.out.print("Da nhan:");
                    }
                } catch (Exception loi) {
                    System.out.print(loi);
                }
            }
        }
    }

    public class ThreadNhanFile extends Thread {

        public void run() {
            try {
                while (true) {//Nếu còn dữ liệu để nhận
                    if (ktNhanfile == 1)//Nếu đang nhận file
                    {
                        txtsend.enable(false);//Không cho người dùng gõ thông báo
                        byte[] buff = new byte[512];//Tạo bộ đệm để nhận
                        buff = gn.NhanByte();//Nhận về 1 dãy các byte lưu vào buff
//Chuyển 1 dãy các byte sang chuỗi
                        String dl = new String(buff, 0, ConnectUtils.DoDaiGoiTinNhan);
                        if (dl.trim().equals("quit")) {//Nếu chuỗi nhận về là quit: kết thúc việc chuyển file
                            f.close();//Đóng và lưu file
                            ktNhanfile = 0;//Chuyển sang chế độ nhận thông báo
                            txtsend.enable(true);//Cho phép gõ thông báo
                            list1.add("Đã Lưu File Vào Ổ ĐĨA D:");//Hiển thị thông báo đã nhận file
                            tdnhanfile.stop();
                        } else {
                            f.write(buff, 0, ConnectUtils.DoDaiGoiTinNhan);//Ghi dãy các byte từ buff vào file
                        }
                    }
                }
            } catch (Exception tt) {
                System.out.print(tt.getMessage());
            }
        }
    }//Kết thức lớp ThreadNhanfile

    public void NapDuLIeuVaoChoice()//Nạp các tài khoản đang sử dụng vào choice
    {
        try {
            choice1.removeAll();//Xóa tất cả dữ liệu trên choice
            TaiKhoan tk = new TaiKhoan();
            ResultSet rs = tk.LayTaiKhoanDangKetNoi(ConnectUtils.TenDn);//Lấy về các tài khoản đang sử dụng
            while (rs.next()) //Nạp vào choice
            {
                String t = rs.getString("TenDangNhap");
                choice1.add(t);
            }
            rs.close();
        } catch (Exception loi) {
            JOptionPane.showMessageDialog(this, loi.getMessage());
        }
    }
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (ConnectUtils.TenDn != "") {
            // TODO add your handling code here:
            gn.MoCong(1261);
            Thread tdnhan = new Thread(new ThreadGoiTinNhan());
            tdnhan.start();//Bắt đầu tuyến đoạn nhận thông báo
            NapDuLIeuVaoChoice();
            this.setTitle("Xin Chào : " + ConnectUtils.TenDn);//Hiển thị tiêu đề của Frame
        } else {
            this.setVisible(false);
            new FrmDN1().setVisible(true);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TaiKhoan tk = new TaiKhoan();
        String IpMayGoiDen = tk.LayIp(choice1.getSelectedItem());
        String dulieugoi = " " + ConnectUtils.TenDn + "(" + tk.LayIp(ConnectUtils.TenDn) + ") :" + txtsend.getText();
        list1.add(dulieugoi);
        gn.Goi(dulieugoi, IpMayGoiDen, 1260);//Gửi dữ liệu

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
//Mở cửa sổ để chọn file
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(this);//Hiển thị cửa sổ
// chooser.getSelectedFile().getPath()): lấy đường dẫn và tên file vừa chọn
// chooser.getSelectedFile()getName();//Lấy tên file vừa chọn
            TaiKhoan tk = new TaiKhoan();
//Lấy Ip của máy cần gửi
            String IpMayGoiDen = tk.LayIp(choice1.getSelectedItem());
//Mở file vừa chọn để đọc
            FileInputStream f = new FileInputStream(chooser.getSelectedFile().getPath());
            byte[] buff = new byte[512];//Tạo bộ đệm để chứa dữ liệu
            String tenfile = "/tf:" + chooser.getSelectedFile().getName();
//Gửi tên file đi
            gn.Goi(tenfile, IpMayGoiDen, 1261);
            Thread.sleep(2);//Dừng chương trình lại 2/1000 giây
            int sb = f.read(buff);//Đọc file tối đa 512 byte, sb; chứa số byte đọc được
            while (sb > 0) //Duyệt file
            {
                gn.GoiByte(buff, sb, IpMayGoiDen, 1261);//Gửi dữ liệu
                Thread.sleep(2);
                sb = f.read(buff, 0, buff.length);//Đọc tiếp dữ liệu
            }
            while (sb > 0);
            String st = new String("quit");//Kết thúc việc gửi
            gn.Goi("quit", IpMayGoiDen, 1261);//Gửi thông báo đã chuyển xong file
            f.close();
            System.out.print("Đã Gửi");
            ktNhanfile = 0;
        } catch (Exception tt) {
            System.out.print(tt);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3MouseClicked
    
    private void jMenuItem3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MousePressed
        // TODO add your handling code here:
       new FrmDK().setVisible(true);
    }//GEN-LAST:event_jMenuItem3MousePressed

    private void jMenu4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MousePressed
       
    }//GEN-LAST:event_jMenu4MousePressed
    
    private void jMenuItem2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MousePressed
        // TODO add your handling code here:
            int e = list1.getItemCount();
        
        if(e>0){
            TinNhan tn = new TinNhan();
            for (int i = 0; i < e; i++) {
                tn.TaoTinNhan(list1.getItem(i), ConnectUtils.TenDn);
            }
            JOptionPane.showMessageDialog(rootPane, "Đã Lưu vào Database");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Chưa Có Dữ Liệu");
        }
    }//GEN-LAST:event_jMenuItem2MousePressed

    private void jMenuItem5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem5MousePressed
        // TODO add your handling code here:
        new FrmHienThiTin().setVisible(true);
    }//GEN-LAST:event_jMenuItem5MousePressed

    private void jMenuItem6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem6MousePressed
        // TODO add your handling code here:
        new FrmDoiMatKhau().setVisible(true);
    }//GEN-LAST:event_jMenuItem6MousePressed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MousePressed
        // TODO add your handling code here:
        ConnectUtils.TenDn = "";
        this.dispose();
        new FrmDN().setVisible(true);
    }//GEN-LAST:event_jMenuItem4MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmClient1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmClient1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmClient1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmClient1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmClient1().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice choice1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private java.awt.List list1;
    private javax.swing.JTextField txtsend;
    // End of variables declaration//GEN-END:variables
}
